name: GitActions Demo1
on: push
jobs:
  GitActions-demo-jobs:
    name: Demo Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a environment
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: taejun
          LAST_NAME: Seo
          AWS_JOB_NAME: taejun.seo
        run: |
          echo $MY_VAR $FIRST_NAME $LAST_NAME.
          echo $MY_VAR $AWS_JOB_NAME.
